### ISSUE TITLE
Doesn't install on Kali 2

### ISSUE THREAD

**Issue by Securityinfos** [El3ct71k/AutoBrowser#3]
Atfer executing pip install requirements.txt

root@kali:~/AutoBrowser# cat /root/.pip/pip.log 
Downloading/unpacking requirements.txt
  Getting page https://pypi.python.org/simple/requirements.txt/
  Could not fetch URL https://pypi.python.org/simple/requirements.txt/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/requirements.txt/ when looking for download links for requirements.txt
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for requirements.txt:
  * https://pypi.python.org/simple/requirements.txt/
  Getting page https://pypi.python.org/simple/requirements.txt/
  Could not fetch URL https://pypi.python.org/simple/requirements.txt/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/requirements.txt/ when looking for download links for requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for requirements.txt

**Comment by realgam3** [comment]
As you can see in the readme file,
Install requirements command is: 
**pip install -r requirements.txt** not **pip install requirements.txt**

Tell me if you have more problems,
If your problem resolved please close the issue.
