### ISSUE TITLE
sudo pip install -r requirements.txt

### ISSUE THREAD

**Issue by CookieChomper** [El3ct71k/AutoBrowser#4]
Linux Installation:

sudo apt-get install python-pip python2.7-dev libxext-dev python-qt4 qt4-dev-tools build-essential nmap
sudo pip install -r requirements.txt

When I enter...
sudo pip install -r requirements.txt

I get the following:
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Please advise....

**Comment by CookieChomper** [comment]
Resolved...created the file myself...

touch 'requirements.txt'
nano requirements.txt

and added the following code 
python-nmap
Ghost.py
colorlog 

then ran the following...
sudo pip install -r requirements.txt

worked perfectly!

**Comment by El3ct71k** [comment]
Fine!
Fill free to get gel anytime from me

Regards,
Nimrod
